apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: expense-app-frontend
spec:
  replicas: 3

  strategy:
    canary:
      stableService: expense-app-frontend
      canaryService: expense-app-frontend-canary
      trafficRouting:
        nginx:
          stableIngress: expense-app-frontend-ingress
      steps:
        - setWeight: 20
        - pause: { duration: 2m }
        - setWeight: 50
        - pause: { duration: 5m }
        - setWeight: 100

  selector:
    matchLabels:
      app: expense-app-frontend

  template:
    metadata:
      labels:
        app: expense-app-frontend
    spec:
      containers:
      - name: expense-app-frontend
        image: expense-app-frontend:1
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
