apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app-frontend-deployment
  labels:
    app: expense-app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-app-frontend
  template:
    metadata:
      labels:
        app: expense-app-frontend
    spec:
      containers:
      - name: expense-app-frontend
        image: tapashranjannandi/expense-app-frontend:5
        ports:
        - containerPort: 3000
